# sonar-project.properties
# Identifiant unique du projet
sonar.projectKey=proj_indiv_ci

# Nom du projet affiché dans SonarQube
sonar.projectName=proj_indiv_ci

# Version du projet
sonar.projectVersion=1.0

# Chemins vers les sources
sonar.sources=frontend,backend

# Encodage des fichiers source
sonar.sourceEncoding=UTF-8
