# Identifiant unique du projet
sonar.projectKey=proj_indiv_ci

# Nom du projet affiché
sonar.projectName=proj_indiv_ci

# Version
sonar.projectVersion=1.0

# On analyse uniquement le code applicatif
sonar.sources=backend,frontend/src

# Encodage
sonar.sourceEncoding=UTF-8

# Exclusions IMPORTANTES
sonar.exclusions=**/node_modules/**,**/coverage/**,**/lcov-report/**,**/build/**,**/dist/**

# Coverage Jest backend + frontend
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
