name: Docker Build & Push to GHCR

on:
  # Permet de lancer manuellement le workflow
  workflow_dispatch:

  # Déclenche automatiquement après le workflow "Node CI"
  workflow_run:
    workflows: ["Node CI"]   # nom exact du premier workflow
    types:
      - complete

jobs:
  build-and-push:
    runs-on: self-hosted   # ton runner Ubuntu

    steps:
      # 1️⃣ Checkout du code
      - uses: actions/checkout@v3

      # 2️⃣ Build de l'image Docker (sans Buildx)
      - name: Build Docker image
        run: docker build -t petite-maison-epouvante:latest .

      # 3️⃣ Nettoyer les anciennes images inutilisées (optionnel)
      - name: Clean dangling images
        run: docker image prune -f

      # 4️⃣ Login sur GitHub Container Registry
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      # 5️⃣ Taguer l'image pour GHCR
      - name: Tag Docker image for GHCR
        run: docker tag petite-maison-epouvante:latest ghcr.io/${{ github.repository_owner }}/petite-maison-epouvante:latest

      # 6️⃣ Push sur GHCR
      - name: Push to GHCR
        run: docker push ghcr.io/${{ github.repository_owner }}/petite-maison-epouvante:latest
