name: Docker Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t petite-maison-epouvante:latest .
      - run: eval $(minikube -p minikube docker-env)
      - run: docker build -t petite-maison-epouvante:latest .
