name: Deploy

on:
  # Permet de lancer manuellement le workflow
  workflow_dispatch:

  # Déclenche automatiquement après le workflow "Node CI"
  workflow_run:
    workflows: ["Node CI"]   # nom exact du premier workflow
    types:
      - complete

jobs:
  deploy:
    runs-on: self-hosted  # Utiliser ton runner Ubuntu

    steps:
      # 1️⃣ Checkout du code (utile pour récupérer les secrets)
      - uses: actions/checkout@v3

      # 2️⃣ Déployer le conteneur Docker
      - name: Deploy Docker container
        run: |
          OWNER=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
          
          docker rm -f petite-maison-epouvante || true
          
          docker run -d -p 80:5000 \
            -e AZURE_STORAGE_ACCOUNT_NAME="${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" \
            -e AZURE_STORAGE_CONTAINER_NAME="${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}" \
            -e MONGO_URI="${{ secrets.MONGO_URI }}" \
            -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            --name petite-maison-epouvante \
            ghcr.io/$OWNER/petite-maison-epouvante:latest
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          