name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Node CI"]
    types: [completed]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Ensure Minikube is running
        run: |
          sudo sysctl -w fs.protected_regular=0
          sudo rm -f /tmp/juju-*

          minikube status || true
          if ! minikube status | grep -q "host: Running"; then
            sudo minikube start --driver=none --cni=flannel
          fi

          kubectl get nodes

          # l'image est déjà sur la VM : on la charge dans minikube (idempotent)
          minikube image load ghcr.io/aminehamzaoui443/petite-maison-epouvante:latest || true



      - name: Deploy to Kubernetes (Minikube)
        run: |
          OWNER=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
          IMAGE="ghcr.io/aminehamzaoui443/petite-maison-epouvante:latest"

          # Namespace
          kubectl apply -f k8s/namespace.yaml

          # Secrets (idempotent)
          kubectl -n pme delete secret pme-secrets --ignore-not-found
          kubectl -n pme create secret generic pme-secrets \
            --from-literal=AZURE_STORAGE_ACCOUNT_NAME="${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" \
            --from-literal=AZURE_STORAGE_CONTAINER_NAME="${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}" \
            --from-literal=MONGO_URI="${{ secrets.MONGO_URI }}" \
            --from-literal=JWT_SECRET="${{ secrets.JWT_SECRET }}"

          # Apply app + HPA
          kubectl apply -f k8s/app.yaml
          kubectl apply -f k8s/hpa.yaml

          # Set image explicitly (avoid stale image)
          kubectl -n pme set image deployment/pme-backend backend="$IMAGE" 

          # Forcer l'utilisation de l'image locale (évite le pull GHCR)
          kubectl -n pme patch deployment pme-backend -p \
          '{"spec":{"template":{"spec":{"containers":[{"name":"backend","imagePullPolicy":"IfNotPresent"}]}}}}'

          # Rollout
          kubectl -n pme rollout status deployment/pme-backend --timeout=180s

          # Show info
          kubectl -n pme get pods -o wide
          kubectl -n pme get svc
          kubectl -n pme get hpa
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}